---
title: "analisis_univariante"
output: html_document
date: "2025-05-26"
---

```{r, include=FALSE}
# Configurar las opciones globalmente para todo el documento
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(ggplot2)
library(dplyr)
library(plotly)
library(kableExtra)
library(haven)
library(reactable)
library(grid)
library(gridExtra)
library(patchwork)
library(paletteer)
library(haven)
library(tidyr)
library(DT)
library(crosstalk)
library(lubridate) 
library(data.table)
library(arrow)
library(scales)
library(forcats)
library(stringr)
library(purrr)
library(ggrepel)
library(gt)

c <- c(
  "#cce7df",  
  "#93a29e",
  "#b7ded2",  
  "#a4c7bd",  
  "#92b1a8",  
  "#809b93",
  "#bfb5b2" ,
  "#6d857e",  
  "#5b6f69",  
  "#495854" ,"#bfb5b2" ,"#cce7df","#92b1a8","#495854" , "#a4c7bd")


```

```{r}
pregnancies_cohort <- readRDS("E:/EMBARAZO/PREGVAL/1-DATOS/3-PROCESADOS/pregnancy_algorithm/pregnancies_cohort_table_6m_lookback.RDS") |> 
  # obtain pregnancies from 01-07-2009
  tidylog::filter(fecha_inicio >= ymd("2009-07-01"))  |>
  distinct()

pregnancies_cohort_hiper=pregnancies_cohort %>% filter(m_hypertension==1) 
```
edad materna
```{r}
summary(pregnancies_cohort_hiper$age)

```




Gráficos:
```{r}


# 1. Histograma de la edad materna
ggplot(pregnancies_cohort_hiper, aes(x = duration)) +
  geom_histogram(bins = 40, fill = "#69b3a2", color = "white") +
  labs(title = "Distribución de la duración del embarazo (días)",
       x = "Duración (días)", y = "Frecuencia") +
  theme_minimal()
summary(as.numeric(pregnancies_cohort_hiper$duration))

ggplot(pregnancies_cohort_hiper, aes(x = tipo_fin, y = as.numeric(duration))) +
  geom_boxplot(fill = "#69b3a2", outlier.alpha = 0.3) +
  labs(title = "Duración del embarazo según tipo de finalización del embarazo",
       x = "Tipo de finalización", y = "Duración (días)") +
  theme_minimal()
```


```{r}
# 2. Boxplot por tipo de finalización del embarazo
ggplot(pregnancies_cohort_hiper, aes(x = tipo_fin, y = age)) +
  geom_boxplot(fill = "#bfb5b2", outlier.alpha = 0.3) +
  labs(title = "Edad materna según tipo de finalización del embarazo",
       x = "Tipo de finalización", y = "Edad materna (años)") +
  theme_minimal()
summary(pregnancies_cohort_hiper$age)
```
```{r}
pregnancies_cohort_hiper = pregnancies_cohort_hiper %>% filter(age>12 & age<55)
# 2. Boxplot por tipo de finalización del embarazo
ggplot(pregnancies_cohort_hiper, aes(x = tipo_fin, y = age)) +
  geom_boxplot(fill = "#bfb5b2", outlier.alpha = 0.3) +
  labs(title = "Edad materna según tipo de finalización del embarazo",
       x = "Tipo de finalización", y = "Edad materna (años)") +
  theme_minimal()
summary(pregnancies_cohort_hiper$age)
```

```{r}
# 3. Frecuencia por país de nacimiento (top 10 más frecuentes)
pregnancies_cohort_hiper %>%
  group_by(pais_nacimiento) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  slice_head(n = 10) %>%
  ggplot(aes(x = reorder(pais_nacimiento, -n), y = n)) +
  geom_bar(stat = "identity", fill = "#cce7df") +
  labs(title = "Top 10 países de nacimiento", x = "País", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
pregnancies_cohort_hiper %>%
  group_by(exclusion_risk) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  slice_head(n = 10) %>%
  ggplot(aes(x = reorder(exclusion_risk, -n), y = n)) +
  geom_bar(stat = "identity", fill = "#cce7df") +
  labs(title = "Riesgo de exclusión", x = "Riesgo de exclusión", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
ruta_archivo <- "E:/VID/ADEPT/1-DATOS/1-BRUTOS/00_POPULATION/SD2782_SIP_SPO_6464_madres_out.enc.txt"
prueba <- read.table(
  file = ruta_archivo,
  sep = "|",
  header = TRUE,
  fileEncoding = "latin1",   # o prueba "UTF-8" si sigue fallando
  stringsAsFactors = FALSE,
  fill = TRUE,
  comment.char = ""
)
```

