---
title: "tabla1_anomalías"
output: html_document
date: "2025-05-14"
---

```{r, include=FALSE}
# Configurar las opciones globalmente para todo el documento
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(ggplot2)
library(dplyr)
library(plotly)
library(kableExtra)
library(reactable)
library(grid)
library(gridExtra)
library(patchwork)
library(paletteer)
library(tidyr)
library(DT)
library(crosstalk)
library(lubridate) 
library(data.table)
library(arrow)
library(scales)
library(forcats)
library(stringr)
library(purrr)
library(ggrepel)
library(gt)
library(haven)
library(formattable)
library(janitor)
library(rstatix)
library(zoo)
library(survival)
#library(epiR)
library(readxl)
library(writexl)
library(epitools)
library(lme4)
library(lmerTest)
c <- c(
  "#cce7df",  
  "#93a29e",
  "#b7ded2",  
  "#a4c7bd",  
  "#92b1a8",  
  "#809b93",
  "#bfb5b2" ,
  "#6d857e",  
  "#5b6f69",  
  "#495854" ,"#bfb5b2" ,"#cce7df","#92b1a8","#495854" , "#a4c7bd")


```

```{r}
#GAIA 10127 embarazos hipertensos
gaia_embarazos_hiper_comp=read.csv("E:/VID/V1/2-SCRIPTS/Jezabel/gaia_embarazos_hiper_comp.csv")
emb = gaia_embarazos_hiper_comp %>% distinct(embarazo_id)

gaia_embarazos_hiper_comp = gaia_embarazos_hiper_comp%>% filter(age>12 & age<55)
gaia_embarazos_hiper_comp <- gaia_embarazos_hiper_comp %>%
  mutate(
    tipo_fin = if_else(tipo_fin == "spontaneous abortion" & duration > 200,
                       "stillbirth",
                       tipo_fin)
  )

gaia_embarazos_hiper_comp = gaia_embarazos_hiper_comp %>% filter(tipo_fin=='livebirth' | tipo_fin =='stillbirth')
gaia_embarazos_hiper_comp <- gaia_embarazos_hiper_comp %>%
  group_by(embarazo_id) %>%
  mutate(tratadas_p1 = ifelse(any(substr(atc_cod, 1, 3) %in% c("C02", "C03", "C07", "C08", "C09") & periodo_exposicion == 1), 1, 0)) %>%
  ungroup()


gaia_embarazos_hiper_comp <- gaia_embarazos_hiper_comp %>%
  group_by(embarazo_id) %>%
  mutate(
    teratogenicos = ifelse(
      any(
        atc_cod %in% c("H02AB", "G03XA01", "J02AC01", "H03BB02", "H03BA02",
                       "N03AG01", "N03AF01", "N03AA02", "N03AB02", "N03AX11", "D10BA01") &
        periodo_exposicion == 1
      ),
      1,
      0
    )
  ) %>%
  ungroup()


corticoesteroides <-c("H02AB") 
antitiroideos     <- c("H03BB02", "H03BA02",'H03BB52' ) #metimazol, propiltiouracilo
antiepilepticos   <- c("N03AG01", "N03AF01", "N03AA02", "N03AB02",'N03AB52', "N03AX11") #valproato, carbamazepina, fenobarbital, fenitoína,topiramate
antimicoticos     <- c("J02AC01") #fluconazole
hormonales        <- c("G03XA01") #danazol
retinoides        <- c("D10BA01", "D10AD04", "D10AD54") #isotretinoin

gaia_embarazos_hiper_comp <- gaia_embarazos_hiper_comp %>%
  group_by(embarazo_id) %>%
  mutate(
    corticoesteroides_p1 = ifelse(any(atc_cod %in% corticoesteroides & periodo_exposicion == 1), 1, 0),
    antitiroideos_p1     = ifelse(any(atc5_cod %in% antitiroideos & periodo_exposicion == 1), 1, 0),
    antiepilepticos_p1   = ifelse(any(atc5_cod %in% antiepilepticos & periodo_exposicion == 1), 1, 0),
    antimicoticos_p1     = ifelse(any(atc5_cod %in% antimicoticos & periodo_exposicion == 1), 1, 0),
    hormonales_p1        = ifelse(any(atc5_cod %in% hormonales & periodo_exposicion == 1), 1, 0),
    retinoides_p1        = ifelse(any(atc5_cod %in% retinoides & periodo_exposicion == 1), 1, 0)
  ) %>%
  ungroup()


pregnancies_cohort_hiper_imc = read.csv("E:/VID/V1/2-SCRIPTS/Jezabel/pregnancies_cohort_hiper_imc.csv")
preg_imc = pregnancies_cohort_hiper_imc %>% select(embarazo_id, value_imc, obesity_final)

gaia_embarazos_hiper_comp = gaia_embarazos_hiper_comp %>% left_join(preg_imc, by='embarazo_id'
                                                                    )
#añadir aborto prev
pregnancies_cohort_hiper_aborto_prev = read.csv("E:/VID/V1/2-SCRIPTS/Jezabel/pregnancies_cohort_hiper_aborto_prev.csv")
preg_aborto_prev = pregnancies_cohort_hiper_aborto_prev %>% select(embarazo_id, prev_aborto)

gaia_embarazos_hiper_comp = gaia_embarazos_hiper_comp %>% left_join(preg_aborto_prev, by='embarazo_id'
                                                                    )
gaia_embarazos_hiper_comp <- gaia_embarazos_hiper_comp %>% mutate(abortion = if_else(tipo_fin =='spontaneous abortion',1,0))
# CARGAMOS LOS DATOS -------------
# Asegurarse que 'exclusion_risk' esté en el formato correcto
gaia_embarazos_disp_ten_hiper_inter <- gaia_embarazos_hiper_comp %>%
  mutate(exclusion_risk = relevel(factor(exclusion_risk), ref = "not at risk"))


gaia_embarazos_disp_ten_hiper_inter <- gaia_embarazos_disp_ten_hiper_inter %>%
  mutate(age_group = cut(
    age,
    breaks = c(-Inf, 24, 29, 34, 39, Inf),
    labels = c("<25", "25-29", "30-34", "35-39", "≥40"),
    right = TRUE
  ),m_obesity_final=obesity_final)
vars = c('age_group','country','exclusion_risk',"m_smoking","m_alcohol","m_drug_abuse","m_diabetes","m_obesity_final","m_lipid",'corticoesteroides_p1',
    'antitiroideos_p1',
    'antiepilepticos_p1',
    'antimicoticos_p1','prev_aborto')
# Seleccionar las variables necesarias y asegurarse que las variables estén en formato correcto
ps_data <- gaia_embarazos_disp_ten_hiper_inter %>%
  select(embarazo_id, o_cong, tratadas_p1, all_of(vars)) %>%
  distinct(embarazo_id, .keep_all = TRUE)
```


# Tabla 1:
```{r}
# FUNCION MODIFICADA
variables_discretas <- function(base, variable, grupo){ # base, v.a. a analizar (discreta) y variable para separar grupos
  # Selecciona los nombres de los grupos
  nombres <- unique(base %>% select({{grupo}}))%>%
  select({{grupo}}) %>% 
  distinct()  #selecciona los nombres de las variables pero como no queremos que sean 0 y 1, los cambiamos
  
  # Convertir la variable y el grupo a símbolos (para cuando se pase el argumento sin comillas)
  variable_sym <- ensym(variable)
  grupo_sym <- ensym(grupo)
  
  # Mutar y preparar los datos para la tabla
  result <-  base %>% 
    mutate(cambio = as_factor(!!variable_sym)) %>%
    mutate(cambio = fct_explicit_na(cambio, na_level = "Missing")) %>%
    tabyl(cambio, {{grupo}}) %>% #tabla cruzada (tipo table)  
    arrange(cambio) %>% 
    #las funciones adorn_*() para 'embellecer' y completar las tablas creadas con tabyl
    adorn_totals("col") %>% #añade el total
    adorn_percentages("col") %>% #pone los porcentajes
    adorn_pct_formatting(digits = 2) %>%
    adorn_ns("front") %>% #hace que e vea el n al lado del %
    select(cambio,Total, as.character(nombres[1,1]), as.character(nombres[2,1])) #selecciona las columns total, sin anomalías y con anomalías  ||  nos quedamos con cambio para quedarse tb con el nombre de las distintas variables
  
  #para que si es binaria conserve solo un nivel:
  if (nrow(result) == 2) {
    result <- result[2, , drop = FALSE]
  }
  
  
  # P-Valor (realiza un test de Chi-cuadrado entre las variables)
  pvalor <- chisq.test(base %>% pull(!!grupo_sym), base %>% pull(!!variable_sym), correct = FALSE)$p.value
  #pull extrae columna como vector
  #diferencia estadísticamente significativa en la proporción de x entre los dos grupos = asociación
  if(pvalor < 0.0001){ #si el p valor es muy pequeño se redondea a 0.001, is no 3 decimales
    pvalor <- "<0.001"
  } else {
    pvalor <- as.character(sprintf("%.3f", pvalor))
  }
  colnames(result)[1] <- "grupo_num"

  result <- cbind(result, pvalor)  # Combinar resultados con el p-valor
  
  return(result)
}
```


```{r}

# PROCESAMIENTO
resultados <- list()
for (var in vars) {
  var_sym <- rlang::sym(var)
  resultado <- variables_discretas(base = ps_data, variable = !!var_sym, grupo = tratadas_p1)
  if (!is.null(resultado)) {
    resultados[[var]] <- resultado
  }
}


# UNIR RESULTADOS
resultados_combined <- bind_rows(resultados, .id = "Variable")



# CALCULAR TOTALES
totales <- ps_data %>% tabyl(tratadas_p1) %>% mutate(n2 = paste0("N=", n)) %>% select(tratadas_p1, n, n2)

totales <- data.frame( # crea la fila de totales
  grupo = "Counts",
  Total = paste0("N=", prettyNum(sum(totales$n), big.mark = ",")),
  tratadas = prettyNum(totales$n2[totales$tratadas_p1 == 1], big.mark = ","),
  no_tratadas = prettyNum(totales$n2[totales$tratadas_p1 == 0], big.mark = ","),
  pvalor = NA
)

# FORMATEO FINAL
tabla1_fin <- resultados_combined %>% select(-Variable)

# Asigna nombres correctos (incluyendo la primera columna, que debe ser el grupo o nivel de variable)
colnames(tabla1_fin) <- c(" ", "Total","Treated", "Untreated",  "P value")

# Asegúrate de que columnas de `totales` tengan exactamente los mismos nombres
colnames(totales) <- c(" ", "Total","Treated", "Untreated",  "P value")

# Une
tabla1_fin <- rbind(totales, tabla1_fin)
rownames(tabla1_fin) <- NULL

filas <- resultados_combined %>% #se apunta en que fila empieza y acaba cada variable
  mutate(numfila = row_number() + 1) %>%  # +1 por la fila de totales
  group_by(Variable) %>%
  summarise(
    inicio = min(numfila),
    fin = max(numfila),
    n_filas = n(),  # cuántas filas tiene
    .groups = "drop"
  ) %>%
  mutate(nom_base = Variable)

for (i in seq_len(nrow(filas))) {
  if (filas$n_filas[i] == 1) { #si solo tiene un nivel
    tabla1_fin[filas$inicio[i], 1] <- filas$nom_base[i] #en la tabla tabla1_fin en esa fila (inicio[i]) y primera columna ([,1]), reemplaza el texto con el nombre base de la variable.
  }
}
```


calculamos diffs medias estandarizadas:

```{r}

library(tableone)
library(survey)
#calculamos los pesos: 
modelo_ps <- glm(tratadas_p1 ~ ., data = ps_data %>% select(-embarazo_id,-o_cong), family = binomial)

# Calcular propensity scores
ps_data$pscore <- predict(modelo_ps, type = "response")

p_tratado <- mean(ps_data$tratadas_p1 == 1)
p_no_tratado <- 1 - p_tratado

# Calcular peso estabilizado
ps_data <- ps_data %>%
  mutate(
    weight_iptw = case_when(
      tratadas_p1 == 1 ~ p_tratado / pscore,
      tratadas_p1 == 0 ~ p_no_tratado / (1 - pscore)
    )
  )


design_ps <- svydesign(ids = ~1, data = ps_data, weights = ~weight_iptw)
```


código sin ejecutar
```{r}
# Obtener matrices con SMD
tabla_sin_peso <- CreateTableOne(vars = vars, strata = "tratadas_p1", data = ps_data, test = FALSE)
tabla_con_peso <- svyCreateTableOne(vars = vars, strata = "tratadas_p1", data = design_ps, test = FALSE)


```
```{r}
# Convertir las tablas completas (con subcategorías y SMD) en data.frame
tabla_sin_df <- print(tabla_sin_peso, smd = TRUE, printToggle = FALSE)
tabla_con_df <- print(tabla_con_peso, smd = TRUE, printToggle = FALSE)

# Convertir a data.frame explícitamente
tabla_sin_df <- as.data.frame(tabla_sin_df)
tabla_con_df <- as.data.frame(tabla_con_df)

# Añadir la variable como columna
tabla_sin_df$Variable <- rownames(tabla_sin_df)
tabla_con_df$Variable <- rownames(tabla_con_df)

# Renombrar columnas de SMD
tabla_sin_df <- tabla_sin_df %>% dplyr::rename(SMD_Before = SMD)
tabla_con_df <- tabla_con_df %>% dplyr::rename(SMD_After = SMD)

```
```{r}

# Crear copia para trabajar
tabla_sin_df <- tabla_sin_df %>%
  mutate(SMD_Before = ifelse(SMD_Before == "", NA, SMD_Before))

# Extraer proporciones y calcular SMD para subcategorías sin SMD
tabla_sin_df <- tabla_sin_df %>%
  mutate(
    p1 = as.numeric(str_extract(`0`, "(?<=\\()\\s*\\d+\\.?\\d*")) / 100,
    p2 = as.numeric(str_extract(`1`, "(?<=\\()\\s*\\d+\\.?\\d*")) / 100
  ) %>%
  mutate(
    SMD_Before = ifelse(
      is.na(SMD_Before) & !is.na(p1) & !is.na(p2),
      round((p1 - p2) / sqrt((p1 * (1 - p1) + p2 * (1 - p2)) / 2), 3),
      SMD_Before
    )
  ) %>%
  select(-p1, -p2)  # quitar columnas auxiliares


# Crear copia para trabajar
tabla_con_df <- tabla_con_df %>%
  mutate(SMD_After = ifelse(SMD_After == "", NA, SMD_After))

# Extraer proporciones y calcular SMD para subcategorías sin SMD
tabla_con_df <- tabla_con_df %>%
  mutate(
    p1 = as.numeric(str_extract(`0`, "(?<=\\()\\s*\\d+\\.?\\d*")) / 100,
    p2 = as.numeric(str_extract(`1`, "(?<=\\()\\s*\\d+\\.?\\d*")) / 100
  ) %>%
  mutate(
    SMD_After = ifelse(
      is.na(SMD_After) & !is.na(p1) & !is.na(p2),
      round((p1 - p2) / sqrt((p1 * (1 - p1) + p2 * (1 - p2)) / 2), 3),
      SMD_After
    )
  ) %>%
  select(-p1, -p2)  # quitar columnas auxiliares

```


```{r}
# Unir las dos tablas por la variable (que incluye subcategorías)
df_smd_completo <- dplyr::left_join(
  tabla_sin_df[, c("Variable", "SMD_Before")],
  tabla_con_df[, c("Variable", "SMD_After")],
  by = "Variable"
)

# Visualizar resultado

df_smd_completo$Variable <- sub(" \\(mean \\(SD\\)\\)$", "", df_smd_completo$Variable)
```

```{r}
# Limpieza de SMDs si están como texto
df_smd_completo <- df_smd_completo %>%
  mutate(
    SMD_Before = ifelse(SMD_Before == "NA", NA, SMD_Before),
    SMD_After = ifelse(SMD_After == "NA", NA, SMD_After)
  )
library(stringr)
df_smd_completo$Variable <- str_trim(df_smd_completo$Variable, side = "both")

```

unimos a tabla1:
```{r}
# Añade columnas vacías para SMD_Before y SMD_After
tabla1_fin$SMD_Before <- NA
tabla1_fin$SMD_After <- NA

# Recorre desde la segunda fila (i=2) y empareja por la columna 1 (nombre variable/subcategoría)
for (i in 2:nrow(tabla1_fin)) {
  var_nombre <- tabla1_fin[i, 1] |> as.character()

  # Buscar fila correspondiente en df_smd_completo
  fila_match <- which(df_smd_completo$Variable == tabla1_fin[i,1])

  # Si hay match, copiar valores
  if (length(fila_match) == 1) {
    tabla1_fin$SMD_Before[i] <- df_smd_completo$SMD_Before[fila_match]
    tabla1_fin$SMD_After[i] <- df_smd_completo$SMD_After[fila_match]
  }
}
```



```{r}
options(knitr.kable.NA = '')
tabla_kable <- kable(tabla1_fin, linesep = "", escape = FALSE, booktabs = TRUE,
                     align = c("l", rep("c", 6))) %>%  # ahora tienes 7 columnas: nombre + 4 + 2 SMDs
  kable_paper("hover", full_width = FALSE) %>%
  row_spec(0, bold = TRUE, extra_css = "vertical-align:middle;border-bottom: 1px solid", background = "#cce7df", color = "black") %>%
  column_spec(1, bold = TRUE, border_right = TRUE, border_left = TRUE, width = "6cm") %>%
  column_spec(2:7, border_left = TRUE)  # Ajustar al nuevo número de columnas


tabla_kable <- reduce(
  seq_len(nrow(filas)), #aquí para cada grupo creará la tabla y aplicará la función .f
  .init = tabla_kable,
  .f = function(tabla, i) {
    is_comorbidity <- grepl("^m_", filas$nom_base[i])
    is_drug <- grepl("_p1$", filas$nom_base[i])
    
    # Saltar filas que luego se agruparán como comorbilidades o drugs
    if (is_comorbidity || is_drug) {
      return(tabla)
    }
    group_rows(
      kable_input = tabla,
      group_label = filas$nom_base[i], # título basándose en la infor de filas de donde empieza y acaba cada variable
      start_row = filas$inicio[i],
      end_row = filas$fin[i],
      underline = TRUE,
      colnum = 1
      )
    
  }
)

# Agrupar comorbilidades (si hay, crea su tabla desde la primera que aprace hasta la ultima y se unen)

comorb_rows <- filas %>% filter(grepl("^m_", nom_base))
if (nrow(comorb_rows) > 0) {
  tabla_kable <- group_rows(
    kable_input = tabla_kable,
    group_label = "Comorbidities",
    start_row = min(comorb_rows$inicio),
    end_row = max(comorb_rows$fin),
    underline = TRUE,
    colnum = 1
  )
}

# Agrupar medicamentos
drug_rows <- filas %>% filter(grepl("_p1$", nom_base))
if (nrow(drug_rows) > 0) {
  tabla_kable <- group_rows(
    kable_input = tabla_kable,
    group_label = "Drugs",
    start_row = min(drug_rows$inicio),
    end_row = max(drug_rows$fin),
    underline = TRUE,
    colnum = 1
  )
}
```


```{r}
tabla_kable <- tabla_kable %>%
  kableExtra::row_spec(
    which(tabla1_fin[[1]] == "prev_aborto"),
    extra_css = "font-weight: normal"
  )

# Reemplazar visualmente los nombres de las comorbilidades y prev_aborto
# Usamos gsub sobre el HTML de salida de kable
tabla_kable <- tabla_kable %>%
  gsub("m_smoking", "Smoking", ., fixed = TRUE) %>%
  gsub("m_alcohol", "Alcohol", ., fixed = TRUE) %>%
  gsub("m_diabetes", "Diabetes", ., fixed = TRUE) %>%
  gsub("m_drug_abuse", "Drug abuse", ., fixed = TRUE) %>%
  gsub("m_lipid", "Lipid", ., fixed = TRUE) %>%
  gsub("m_obesity_final", "Obesity", ., fixed = TRUE) %>%
  gsub("corticoesteroides_p1", "Corticosteroids", ., fixed = TRUE) %>%
  gsub("antitiroideos_p1", "Antithyroid drugs", ., fixed = TRUE) %>%
  gsub("antiepilepticos_p1", "Antiepileptics", ., fixed = TRUE)%>%
  gsub("antimicoticos_p1", "Antimycotics", ., fixed = TRUE) %>% 
  gsub("prev_aborto", "Previous abortion", ., fixed = TRUE)
tabla_kable
```


